// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fdvvphrhmjemnsylufsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZkdnZwaHJobWplbW5zeWx1ZnN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMzczNTUsImV4cCI6MjA2MDgxMzM1NX0.3-hJzR4Qhf66KWCYHG6rtQV4Oa-gkIN2cT3OQbI5xlU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);